name: Party-Toggle-For-PAF
version: ${project.version}
author: Simonsator
depends: [PartyAndFriends]
main: de.simonsator.partyandfriends.partytoggle.PTMain
description: An add-on for party and friends to add /party toggle
